const CATEGORIES_ACTION_TYPES = {
  FETH_CATEGORIES_START: 'category/FETCH_CATEGORY_START',
  FETH_CATEGORIES_SUCCESS: 'category/FETCH_CATEGORY_SUCCESS',
  FETH_CATEGORIES_FAILED: 'category/FETCH_CATEGORY_FAILED'
};

export default CATEGORIES_ACTION_TYPES;
